### ISSUE TITLE
Relative model fit 산출 관련 문의 드립니다.

### ISSUE THREAD

**Issue by Seung1Park** [hyunsooseol/snowLatent#1]
안녕하세요 교수님, 워크샵에 참여했던 학생입니다.
메일 남겨드렸으나 확인하시지 못하는 것 같아 깃허브에서 인사드리게 되었습니다. :)

모듈 작동시에 변수 개수가 늘어날 경우 Relative model fit 이 산출되지 않는 경우가 있습니다.
여러 방법을 테스트해 본 결과, 특정 변수의 문제이거나 문제가 발생하는 변수 개수는 특정되지는 않았습니다.
말 그대로 랜덤하게 결과가 산출되지 않는 것으로 보입니다. 보통 6~7개 사이에서 문제가 발생합니다.

혹시 데이터 상 문제가 있는 것일까요? 혹시 확인 필요하실지 몰라 사용한 데이터는 메일에 첨부드렸습니다..!
감사합니다.

**Comment by hyunsooseol** [comment]
[Seung1Park](https://github.com/Seung1Park) 님께 

제가 개인적인 일로 out of office 해서 연락을 못 드렸습니다. 편차 결과표는 glca 패키지가 결과를 보여주지 않으면 모듈에서는 빈 공란으로 출력이 됩니다. 혹시 모르니 메일에 데이타가 첨부되어 있지 않아서 다시 보내주시면 한번 확인하겠습니다. 감사합니다.
