### ISSUE TITLE
Probabilities not properly assigned to rows if filter is applied

### ISSUE THREAD

**Issue by sschwarzinger** [hyunsooseol/snowLatent#2]
Hi,

LCA in snowLatent works pretty fine, however I ran into one limitation:
If a filter is applied, probabilities like class membership are not properly assigned to the rows. 

Concretely, if e.g. 100 of 1.000 cases are selected via a filter and LCA is performed, the probabilities are assigned to the first 100 cases instead of the 100 selected cases. 

Is there any workaround at the moment?

Best,
Stephan

**Comment by hyunsooseol** [comment]
[sschwarzinger](https://github.com/sschwarzinger)

Could you share the file that occurs error as a zip file in here? I think that is a limitation not error.

Best Regards
Seol

**Comment by sschwarzinger** [comment]
Hi,

it happens with every dataset, independent from the number of rows.

The only workaround I figured out is to remove the cases to be filtered out from the dataset and run the LCA on this hard-filtered dataset.

Best regards,
Stephan

**Comment by hyunsooseol** [comment]
Hi Stephan
Thanks for your comments

As you might know, the module has been developed by module developer not jamovi base team.
So sometimes it causes conflicts between functions.

Cheers
Seol
