### ISSUE TITLE
 Classify membership using multigroup and multivel LCA

### ISSUE THREAD

**Issue by andremonezi** [hyunsooseol/snowLatent#3]
Dear Dr. Seol, 

Based on my experience with your snowLatent package (Multiple and Multilevel) I realized that there is no option to classify membership, as in a classic LCA, wich means that it is not possible to input the classification of each participant and run additional analyses. Using the classic LCA (first analysis of the package), this is fully possible. Could you please add this option, please?

Another request: In the Multiple and Multilevel analyses, the system shows the "item response probabilities by class" only for the overall sample, but does not separate it for each of the groups. It is certain that this separation will help us better understand the behavior of the classes, as well as provide material for scientific articles. Note that the "class prevalences by group" already appears separated from each group.

In addition, I would like to congratulate you on your package, as it is helping us a lot and making LCA more accessible to researchers.

Best regards,

**Comment by hyunsooseol** [comment]
Dear Dr. [andremonezi](https://github.com/andremonezi)

Thanks for using snowLatent module. Regarding the first question, it's not possible to add class membership to datasheet according to the ID number with multiple group and multilevel model.
glca R package does not provide the information about the class membership along with ID numbers.

Regarding the Second question, do you want the plot shown below? If yes, I will update it soon.
![image](https://user-images.githubusercontent.com/37318620/212533456-25e016bf-c261-451f-a98d-b951f43403e4.png)

Best Regards
Seol

**Comment by andremonezi** [comment]
Dear Dr. Seol, 

In regards to the first question, is there another way to add class membership based on ID number? 

If you know of any R packages that do this, or if I have to do it by hand, I'd like to know about them. I thought I'd test for invariance (e.g. gender) between the groups using the multigroup LCA module and then make two separate spreadsheets, one for one group (men, for example) and one for women, and do classical LCAs for each group. Is that right?

Regarding the second question, it's these plots!

Thanks, best regards

**Comment by hyunsooseol** [comment]
Dear Dr. [andremonezi](https://github.com/andremonezi)

Thanks for your reply. Regarding the first question, I can not explain the algorithm about the multi group membership since I am not a author of glca R package. so, you might ask it to the glca authors directly and tell me how to do that later.  Anyway, you will get the posterior probabilities by clicking '**posterior'** option.
Regarding the plot, I will update it this weekend and let you know.
and you might read the [documentation ](https://docs.google.com/viewer?a=v&pid=sites&srcid=a29yZWEuYWMua3J8a3VzdGF0bGFifGd4OjU0Nzc0NjU4OGJkODVjNDk) carefully in the result screen.

Best Regards
Seol

**Comment by hyunsooseol** [comment]
Dear Dr. [andremonezi](https://github.com/andremonezi)

With posterior probability by group in jamovi, you can use R to get class membership, for example, `Member = factor(apply(data, 1, which.max))`

**Comment by hyunsooseol** [comment]
Dear Dr. [andremonezi](https://github.com/andremonezi)

you can use Rj + module with posterior probabilities to get class membership. I will show you the example shown below.
![이미지 001](https://user-images.githubusercontent.com/37318620/212787686-5cc0f80b-f0b0-4497-9e4f-784be6432287.png)

Best Regards
Seol

**Comment by andremonezi** [comment]
Dear Dr. Seol, good morning!

Thank you for your prompt reply and the example. I'll try it out and if I have any questions, I'll let you know.

Thanks a lot

André Monezi

**Comment by hyunsooseol** [comment]
Dear Dr. [andremonezi](https://github.com/andremonezi)

You can update the newest version of snowLatent module in jamovi library now.
Thanks for your suggestions.

Best Regards
Seol
